name: sunnyside
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-Bold.ttf
          weight: 700
        - asset: assets/fonts/Fraunces-Black.ttf
          weight: 900
